TARGET = p1 p2 p3 p4 p5 p7

all : $(TARGET)

p1 :
	g++ -o p1 p2_1.cpp

p2 :
	g++ -o p2 p2_2.cpp

p3: 
	g++ -o p3 WindGauge.cpp testWindGauge.cpp

p4 :
	g++ -o p4 p2_4.cpp

p5 :
	g++ -o p5 p2_5.cpp

p7 : 
	g++ -o p7 p2_7.cpp

clean :
	rm -f $(TARGET)
