CC = g++
TARGET = p1 p2 p3 p4 p5

all : $(TARGET)

p1 : 
	$(CC) -o p1 p_1.1_Main.cpp

p2 :
	$(CC) -o p2 testStack.cpp

p3 :
	$(CC) -o p3 testLinkedList.cpp

p4 :
	$(CC) -o p4 p_1.4_Main.cpp

p5 :
	$(CC) -o p5 p_1.5_Main.cpp

clean:
	rm -f $(TARGET)
